/*
Navicat MySQL Data Transfer

Source Server         : 本机mysql5.7
Source Server Version : 50717
Source Host           : localhost:3306
Source Database       : db_kwm

Target Server Type    : MYSQL
Target Server Version : 50717
File Encoding         : 65001

Date: 2017-03-04 16:50:47
*/
use db_kwm;
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for flow_goods
-- ----------------------------
DROP TABLE IF EXISTS `flow_goods`;
CREATE TABLE `flow_goods` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `GOODS_CHANNEL_ID` bigint(20) NOT NULL,
  `GOODS_NAME` varchar(255) NOT NULL,
  `GOODS_DESC` varchar(512) DEFAULT NULL,
  `GOODS_TP_ID` bigint(20) NOT NULL COMMENT '运营商ID',
  `GOODS_PROVINCE_ID` int(11) NOT NULL COMMENT '适用范围（0：全国，x：某个省）',
  `GOODS_PRICE` decimal(10,2) NOT NULL COMMENT '2位小数',
  `GOODS_AMOUNT` int(10) NOT NULL COMMENT '库存，若为-1则无限',
  `GOODS_STATE` varchar(128) NOT NULL COMMENT '商品状态（0,：已下架，1：已上架，x:其他状态）',
  `GOODS_EXPIRE` datetime DEFAULT NULL COMMENT '到期日期，如果为NULL，则此字段无效',
  `GMT_CREATE` datetime NOT NULL,
  `GMT_UPDATE` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_GOODS_TP` (`GOODS_TP_ID`),
  KEY `FK_GOODS_CHANNEL` (`GOODS_CHANNEL_ID`) USING BTREE,
  KEY `FK_GOODS_PROVINCE_idx` (`GOODS_PROVINCE_ID`),
  CONSTRAINT `FK_GOODS_CHANNEL` FOREIGN KEY (`GOODS_CHANNEL_ID`) REFERENCES `flow_channel` (`ID`),
  CONSTRAINT `FK_GOODS_PROVINCE` FOREIGN KEY (`GOODS_PROVINCE_ID`) REFERENCES `resource_area` (`id`),
  CONSTRAINT `FK_GOODS_TP` FOREIGN KEY (`GOODS_TP_ID`) REFERENCES `flow_telecom_operator` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of flow_goods
-- ----------------------------
/* 渠道1 辽宁 移动 30M */
INSERT INTO `flow_goods` (GOODS_CHANNEL_ID,GOODS_NAME,GOODS_DESC,GOODS_TP_ID,GOODS_PROVINCE_ID,GOODS_PRICE,GOODS_AMOUNT,GOODS_STATE,GOODS_EXPIRE,GMT_CREATE,GMT_UPDATE) VALUES ('1', '30M', null, '1', '210000', '9.99', '-1', '1', NULL, NOW(), NOW());
/* 渠道2 辽宁 移动 30M */
INSERT INTO `flow_goods` (GOODS_CHANNEL_ID,GOODS_NAME,GOODS_DESC,GOODS_TP_ID,GOODS_PROVINCE_ID,GOODS_PRICE,GOODS_AMOUNT,GOODS_STATE,GOODS_EXPIRE,GMT_CREATE,GMT_UPDATE) VALUES ('2', '30M', null, '1', '210000', '5.99', '-1', '1', NULL, NOW(), NOW());
/* 渠道3 辽宁 移动 30M */
INSERT INTO `flow_goods` (GOODS_CHANNEL_ID,GOODS_NAME,GOODS_DESC,GOODS_TP_ID,GOODS_PROVINCE_ID,GOODS_PRICE,GOODS_AMOUNT,GOODS_STATE,GOODS_EXPIRE,GMT_CREATE,GMT_UPDATE) VALUES ('3', '30M', null, '1', '210000', '4.99', '-1', '1', NULL, NOW(), NOW());
/* 渠道3 全国 移动 30M */
INSERT INTO `flow_goods` (GOODS_CHANNEL_ID,GOODS_NAME,GOODS_DESC,GOODS_TP_ID,GOODS_PROVINCE_ID,GOODS_PRICE,GOODS_AMOUNT,GOODS_STATE,GOODS_EXPIRE,GMT_CREATE,GMT_UPDATE) VALUES ('3', '30M', null, '1', '0', '12.89', '-1', '1', NULL, NOW(), NOW());

/* beigin */
/* 渠道3 全国 移动 30M */
INSERT INTO `flow_goods` (GOODS_CHANNEL_ID,GOODS_NAME,GOODS_DESC,GOODS_TP_ID,GOODS_PROVINCE_ID,GOODS_PRICE,GOODS_AMOUNT,GOODS_STATE,GOODS_EXPIRE,GMT_CREATE,GMT_UPDATE) VALUES ('3', '30M', null, '1', '0', '11.66', '-1', '1', NULL, NOW(), NOW());
/* 渠道3 全国 移动 30M */
INSERT INTO `flow_goods` (GOODS_CHANNEL_ID,GOODS_NAME,GOODS_DESC,GOODS_TP_ID,GOODS_PROVINCE_ID,GOODS_PRICE,GOODS_AMOUNT,GOODS_STATE,GOODS_EXPIRE,GMT_CREATE,GMT_UPDATE) VALUES ('3', '30M', null, '1', '0', '10.66', '-1', '1', NULL, NOW(), NOW());
/* 渠道3 全国 移动 30M */
INSERT INTO `flow_goods` (GOODS_CHANNEL_ID,GOODS_NAME,GOODS_DESC,GOODS_TP_ID,GOODS_PROVINCE_ID,GOODS_PRICE,GOODS_AMOUNT,GOODS_STATE,GOODS_EXPIRE,GMT_CREATE,GMT_UPDATE) VALUES ('3', '30M', null, '1', '0', '10.68', '-1', '1', NULL, NOW(), NOW());
/* end */

/* 渠道3 全国 移动 30M */
INSERT INTO `flow_goods` (GOODS_CHANNEL_ID,GOODS_NAME,GOODS_DESC,GOODS_TP_ID,GOODS_PROVINCE_ID,GOODS_PRICE,GOODS_AMOUNT,GOODS_STATE,GOODS_EXPIRE,GMT_CREATE,GMT_UPDATE) VALUES ('3', '30M', null, '1', '0', '13.66', '-1', '1', NULL, NOW(), NOW());
/* 渠道3 全国 移动 30M */
INSERT INTO `flow_goods` (GOODS_CHANNEL_ID,GOODS_NAME,GOODS_DESC,GOODS_TP_ID,GOODS_PROVINCE_ID,GOODS_PRICE,GOODS_AMOUNT,GOODS_STATE,GOODS_EXPIRE,GMT_CREATE,GMT_UPDATE) VALUES ('3', '30M', null, '1', '0', '16.66', '-1', '1', NULL, NOW(), NOW());


/* 渠道1 北京 移动 100M */
INSERT INTO `flow_goods` (GOODS_CHANNEL_ID,GOODS_NAME,GOODS_DESC,GOODS_TP_ID,GOODS_PROVINCE_ID,GOODS_PRICE,GOODS_AMOUNT,GOODS_STATE,GOODS_EXPIRE,GMT_CREATE,GMT_UPDATE) VALUES ('1', '100M', null, '1', '110000', '10.89', '-1', '1', NULL, NOW(), NOW());
/* 渠道2 北京 电信 100M */
INSERT INTO `flow_goods` (GOODS_CHANNEL_ID,GOODS_NAME,GOODS_DESC,GOODS_TP_ID,GOODS_PROVINCE_ID,GOODS_PRICE,GOODS_AMOUNT,GOODS_STATE,GOODS_EXPIRE,GMT_CREATE,GMT_UPDATE) VALUES ('2', '100M', null, '2', '110000', '10.99', '-1', '1', NULL, NOW(), NOW());
/* 渠道3 北京 联通 100M */
INSERT INTO `flow_goods` (GOODS_CHANNEL_ID,GOODS_NAME,GOODS_DESC,GOODS_TP_ID,GOODS_PROVINCE_ID,GOODS_PRICE,GOODS_AMOUNT,GOODS_STATE,GOODS_EXPIRE,GMT_CREATE,GMT_UPDATE) VALUES ('3', '100M', null, '3', '110000', '11.99', '-1', '1', NULL, NOW(), NOW());
/* 渠道3 全国 移动 100M */
INSERT INTO `flow_goods` (GOODS_CHANNEL_ID,GOODS_NAME,GOODS_DESC,GOODS_TP_ID,GOODS_PROVINCE_ID,GOODS_PRICE,GOODS_AMOUNT,GOODS_STATE,GOODS_EXPIRE,GMT_CREATE,GMT_UPDATE) VALUES ('3', '100M', null, '1', '0', '12.99', '-1', '1', NULL, NOW(), NOW());

/* 渠道1 辽宁 电信 30M */
INSERT INTO `flow_goods` (GOODS_CHANNEL_ID,GOODS_NAME,GOODS_DESC,GOODS_TP_ID,GOODS_PROVINCE_ID,GOODS_PRICE,GOODS_AMOUNT,GOODS_STATE,GOODS_EXPIRE,GMT_CREATE,GMT_UPDATE) VALUES ('1', '30M', null, '2', '210000', '9.99', '-1', '1', NULL, NOW(), NOW());
/* 渠道2 辽宁 联通 30M */
INSERT INTO `flow_goods` (GOODS_CHANNEL_ID,GOODS_NAME,GOODS_DESC,GOODS_TP_ID,GOODS_PROVINCE_ID,GOODS_PRICE,GOODS_AMOUNT,GOODS_STATE,GOODS_EXPIRE,GMT_CREATE,GMT_UPDATE) VALUES ('2', '30M', null, '3', '210000', '5.99', '-1', '1', NULL, NOW(), NOW());
/* 渠道1 全国 移动 30M */
INSERT INTO `flow_goods` (GOODS_CHANNEL_ID,GOODS_NAME,GOODS_DESC,GOODS_TP_ID,GOODS_PROVINCE_ID,GOODS_PRICE,GOODS_AMOUNT,GOODS_STATE,GOODS_EXPIRE,GMT_CREATE,GMT_UPDATE) VALUES ('1', '30M', null, '1', '0', '15.99', '-1', '1', NULL, NOW(), NOW());

/* 渠道1 辽宁 移动 50M */
INSERT INTO `flow_goods` (GOODS_CHANNEL_ID,GOODS_NAME,GOODS_DESC,GOODS_TP_ID,GOODS_PROVINCE_ID,GOODS_PRICE,GOODS_AMOUNT,GOODS_STATE,GOODS_EXPIRE,GMT_CREATE,GMT_UPDATE) VALUES ('1', '50M', null, '1', '210000', '14.99', '-1', '1', NULL, NOW(), NOW());
/* 渠道1 辽宁 移动 100M */
INSERT INTO `flow_goods` (GOODS_CHANNEL_ID,GOODS_NAME,GOODS_DESC,GOODS_TP_ID,GOODS_PROVINCE_ID,GOODS_PRICE,GOODS_AMOUNT,GOODS_STATE,GOODS_EXPIRE,GMT_CREATE,GMT_UPDATE) VALUES ('1', '100M', null, '1', '210000', '19.99', '-1', '1', NULL, NOW(), NOW());

/* 渠道1 辽宁 移动 200M */
INSERT INTO `flow_goods` (GOODS_CHANNEL_ID,GOODS_NAME,GOODS_DESC,GOODS_TP_ID,GOODS_PROVINCE_ID,GOODS_PRICE,GOODS_AMOUNT,GOODS_STATE,GOODS_EXPIRE,GMT_CREATE,GMT_UPDATE) VALUES ('1', '200M', null, '1', '210000', '21.99', '-1', '1', NULL, NOW(), NOW());
/* 渠道3 全国 移动 200M */
INSERT INTO `flow_goods` (GOODS_CHANNEL_ID,GOODS_NAME,GOODS_DESC,GOODS_TP_ID,GOODS_PROVINCE_ID,GOODS_PRICE,GOODS_AMOUNT,GOODS_STATE,GOODS_EXPIRE,GMT_CREATE,GMT_UPDATE) VALUES ('3', '200M', null, '1', '0', '23.99', '-1', '1', NULL, NOW(), NOW());

/* 渠道1 辽宁 移动 500M */
INSERT INTO `flow_goods` (GOODS_CHANNEL_ID,GOODS_NAME,GOODS_DESC,GOODS_TP_ID,GOODS_PROVINCE_ID,GOODS_PRICE,GOODS_AMOUNT,GOODS_STATE,GOODS_EXPIRE,GMT_CREATE,GMT_UPDATE) VALUES ('1', '500M', null, '1', '210000', '31.99', '-1', '1', NULL, NOW(), NOW());
/* 渠道3 全国 移动 500M */
INSERT INTO `flow_goods` (GOODS_CHANNEL_ID,GOODS_NAME,GOODS_DESC,GOODS_TP_ID,GOODS_PROVINCE_ID,GOODS_PRICE,GOODS_AMOUNT,GOODS_STATE,GOODS_EXPIRE,GMT_CREATE,GMT_UPDATE) VALUES ('3', '500M', null, '1', '0', '33.99', '-1', '1', NULL, NOW(), NOW());

/* 渠道1 辽宁 移动 1000M */
INSERT INTO `flow_goods` (GOODS_CHANNEL_ID,GOODS_NAME,GOODS_DESC,GOODS_TP_ID,GOODS_PROVINCE_ID,GOODS_PRICE,GOODS_AMOUNT,GOODS_STATE,GOODS_EXPIRE,GMT_CREATE,GMT_UPDATE) VALUES ('1', '1000M', null, '1', '210000', '41.99', '-1', '1', NULL, NOW(), NOW());
/* 渠道3 全国 移动 1000M */
INSERT INTO `flow_goods` (GOODS_CHANNEL_ID,GOODS_NAME,GOODS_DESC,GOODS_TP_ID,GOODS_PROVINCE_ID,GOODS_PRICE,GOODS_AMOUNT,GOODS_STATE,GOODS_EXPIRE,GMT_CREATE,GMT_UPDATE) VALUES ('3', '1000M', null, '1', '0', '43.99', '-1', '1', NULL, NOW(), NOW());

/* 渠道1 辽宁 移动 2000M */
INSERT INTO `flow_goods` (GOODS_CHANNEL_ID,GOODS_NAME,GOODS_DESC,GOODS_TP_ID,GOODS_PROVINCE_ID,GOODS_PRICE,GOODS_AMOUNT,GOODS_STATE,GOODS_EXPIRE,GMT_CREATE,GMT_UPDATE) VALUES ('1', '2000M', null, '1', '210000', '61.99', '-1', '1', NULL, NOW(), NOW());
/* 渠道3 全国 移动 2000M */
INSERT INTO `flow_goods` (GOODS_CHANNEL_ID,GOODS_NAME,GOODS_DESC,GOODS_TP_ID,GOODS_PROVINCE_ID,GOODS_PRICE,GOODS_AMOUNT,GOODS_STATE,GOODS_EXPIRE,GMT_CREATE,GMT_UPDATE) VALUES ('3', '2000M', null, '1', '0', '63.99', '-1', '1', NULL, NOW(), NOW());
